export const data = [
  {
    name: "City 1",
    full_name: "N/A",
    summary: {
      continent: "N/A",
      coordinates: { east: 0.0, north: 0.0, south: 0.0, west: 0.0 },
      summary: "N/A",
    },
    scores: {
      housing: 0.0,
      cost_of_living: 0.0,
      startups: 0.0,
      venture_capital: 0.0,
      travel_connectivity: 0.0,
      commute: 0.0,
      business_freedom: 0.0,
      safety: 0.0,
      health_care: 0.0,
      education: 0.0,
      environmental_quality: 0.0,
      economy: 0.0,
      taxation: 0.0,
      internet_access: 0.0,
      leisure_and_culture: 0.0,
      tolerance: 0.0,
      outdoors: 0.0,
      teleport_city_score: 0.0,
    },
    details: {
      image_photographer: "N/A",
      image_web_url:
        "https://d13k13wj6adfdf.cloudfront.net/urban_areas/atlanta_web-01e0d78232.jpg",
      image_mobile_url: "N/A",
      population_size_in_millions: 0.0,
      average_costs: {
        consumer_price_index: 0.0,
        apples_per_kg: 0.0,
        bread: 0.0,
        cappuccino: 0.0,
        cinema: 0.0,
        fitness_club: 0.0,
        import_beer: 0.0,
        public_transport: 0.0,
        lunch_meal: 0.0,
        taxi: 0.0,
        restaurant_price_index: 0.0,
        sales_tax: 0.0,
      },
      culture: {
        art_galleries: 0,
        movie_theaters: 0,
        comedy_clubs: 0,
        concert_venues: 0,
        historical_sites: 0,
        museums: 0,
        performing_arts_venues: 0,
        sports_venues: 0,
        zoos: 0,
      },
      housing: {
        large_apartment: 0.0,
        medium_apartment: 0.0,
        small_apartment: 0.0,
      },
    },
  },
  {
    name: "City 2",
    full_name: "N/A",
    summary: {
      continent: "N/A",
      coordinates: { east: 0.0, north: 0.0, south: 0.0, west: 0.0 },
      summary: "N/A",
    },
    scores: {
      housing: 0.0,
      cost_of_living: 0.0,
      startups: 0.0,
      venture_capital: 0.0,
      travel_connectivity: 0.0,
      commute: 0.0,
      business_freedom: 0.0,
      safety: 0.0,
      health_care: 0.0,
      education: 0.0,
      environmental_quality: 0.0,
      economy: 0.0,
      taxation: 0.0,
      internet_access: 0.0,
      leisure_and_culture: 0.0,
      tolerance: 0.0,
      outdoors: 0.0,
      teleport_city_score: 0.0,
    },
    details: {
      image_photographer: "N/A",
      image_web_url:
        "https://d13k13wj6adfdf.cloudfront.net/urban_areas/atlanta_web-01e0d78232.jpg",
      image_mobile_url: "N/A",
      population_size_in_millions: 0.0,
      average_costs: {
        consumer_price_index: 0.0,
        apples_per_kg: 0.0,
        bread: 0.0,
        cappuccino: 0.0,
        cinema: 0.0,
        fitness_club: 0.0,
        import_beer: 0.0,
        public_transport: 0.0,
        lunch_meal: 0.0,
        taxi: 0.0,
        restaurant_price_index: 0.0,
        sales_tax: 0.0,
      },
      culture: {
        art_galleries: 0,
        movie_theaters: 0,
        comedy_clubs: 0,
        concert_venues: 0,
        historical_sites: 0,
        museums: 0,
        performing_arts_venues: 0,
        sports_venues: 0,
        zoos: 0,
      },
      housing: {
        large_apartment: 0.0,
        medium_apartment: 0.0,
        small_apartment: 0.0,
      },
    },
  },
  {
    name: "City 3",
    full_name: "N/A",
    summary: {
      continent: "N/A",
      coordinates: { east: 0.0, north: 0.0, south: 0.0, west: 0.0 },
      summary: "N/A",
    },
    scores: {
      housing: 0.0,
      cost_of_living: 0.0,
      startups: 0.0,
      venture_capital: 0.0,
      travel_connectivity: 0.0,
      commute: 0.0,
      business_freedom: 0.0,
      safety: 0.0,
      health_care: 0.0,
      education: 0.0,
      environmental_quality: 0.0,
      economy: 0.0,
      taxation: 0.0,
      internet_access: 0.0,
      leisure_and_culture: 0.0,
      tolerance: 0.0,
      outdoors: 0.0,
      teleport_city_score: 0.0,
    },
    details: {
      image_photographer: "N/A",
      image_web_url:
        "https://d13k13wj6adfdf.cloudfront.net/urban_areas/atlanta_web-01e0d78232.jpg",
      image_mobile_url: "N/A",
      population_size_in_millions: 0.0,
      average_costs: {
        consumer_price_index: 0.0,
        apples_per_kg: 0.0,
        bread: 0.0,
        cappuccino: 0.0,
        cinema: 0.0,
        fitness_club: 0.0,
        import_beer: 0.0,
        public_transport: 0.0,
        lunch_meal: 0.0,
        taxi: 0.0,
        restaurant_price_index: 0.0,
        sales_tax: 0.0,
      },
      culture: {
        art_galleries: 0,
        movie_theaters: 0,
        comedy_clubs: 0,
        concert_venues: 0,
        historical_sites: 0,
        museums: 0,
        performing_arts_venues: 0,
        sports_venues: 0,
        zoos: 0,
      },
      housing: {
        large_apartment: 0.0,
        medium_apartment: 0.0,
        small_apartment: 0.0,
      },
    },
  },
];
export default data;
